DEBUG = True
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:Devil123@127.0.0.1/FurnitoData?charset=utf8'
json_store = '/home/boyang/Documents/json/'
file_path = "/home/boyang/Documents/furniture/"
temp_path = "/home/boyang/Documents/temp.txt"
posting_list_path = "/home/boyang/furnito_webapp/app/data/posting_list.json"
vector_space_path = "/home/boyang/furnito_webapp/app/data/vector_space.csv"
probability_space_path = "/home/boyang/furnito_webapp/app/data/probability_space.csv"
doc_length_path = "/home/boyang/furnito_webapp/app/data/doc_length.json"
sentiment_path = "/home/boyang/furnito_webapp/app/data/sentiment_dictionary.csv"